version: '3.8'

services:
  web:
    build:
      context: .
    container_name: guid_bot
    restart: always
    env_file:
      - .env
    network_mode: 'host'
    volumes:
      - .:/app
      - media:/app/src/media
    command: sh -c "sh scripts/migration.sh"

volumes:
  media:
